### PR TITLE
Parameterize ocaml-variants information as Docker environment variables

### PR DESCRIPTION
**Pull request by shakthimaan**
* Added support for the following Makefile variables that can be passed as an environment for use with current-bench and Docker:
1. SANDMARK_DUNE_VERSION
2. SANDMARK_URL
3. SANDMARK_REMOVE_PACKAGES
4. SANDMARK_OVERRIDE_PACKAGES
* Updated README documentation on the usage of the above variables.
* The changes support use of `ocaml-versions/*.json` or using the above variables to dynamically run Sandmark.

### CODE REVIEW

**Comment by shubhamkumar13** [comment]
I tried to reproduce a similar result to the CI checks by manually running this branch on turing (I followed the steps mentioned in `.drone.yml`) for parallel and serial benchmarks but a number of dependencies seem to break. 

I even tried upgrading opam because I might not have the latest changes to the packages (`opam update` && `opam upgrade`) but that didn't make any difference.

I don't know if I'm doing something wrong here 😅, I even re-checked if I was on `dev/parameterize-ocaml-variant-for-docker` branch while running the test but I'm getting a different result.

The error log on turing

```bash
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlbuild failed at "/usr/bin/make check-if-preinstalled all opam-install".
[ERROR] The compilation of integers failed at "/home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p integers -j 27".
[ERROR] The compilation of sexplib0 failed at "/home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p sexplib0 -j 27".
[ERROR] The compilation of biniou failed at "/home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p biniou -j 27".
[ERROR] The compilation of ocamlfind failed at "/usr/bin/make all".

#=== ERROR while compiling sexplib0.v0.15.0 ===================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.00.0+trunk | pinned(git+https://github.com/shakthimaan/sexplib0.git#multicore#0ac73c77)
# path                 ~/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/sexplib0.v0.15.0
# command              ~/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p sexplib0 -j 27
# exit-code            1
# env-file             ~/shakti/sandmark/_opam/log/sexplib0-2576049-9d9583.env
# output-file          ~/shakti/sandmark/_opam/log/sexplib0-2576049-9d9583.out
### output ###
# [...]
#       ocamlc src/.sexplib0.objs/byte/sexplib0__Sexp_conv.{cmo,cmt} (exit 2)
# (cd _build/default && /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.sexplib0.objs/byte -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/byte/sexplib0__Sexp_conv.cmo -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 447, characters 32-46:
# 447 |     ; ( [%extension_constructor Stream.Failure]
#                                       ^^^^^^^^^^^^^^
# Error: Unbound module Stream
#     ocamlopt src/.sexplib0.objs/native/sexplib0__Sexp_conv.{cmx,o} (exit 2)
# (cd _build/default && /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/ocamlopt.opt -w -40 -g -I src/.sexplib0.objs/byte -I src/.sexplib0.objs/native -intf-suffix .ml -no-alias-deps -open Sexplib0__ -o src/.sexplib0.objs/native/sexplib0__Sexp_conv.cmx -c -impl src/sexp_conv.ml)
# File "src/sexp_conv.ml", line 447, characters 32-46:
# 447 |     ; ( [%extension_constructor Stream.Failure]
#                                       ^^^^^^^^^^^^^^
# Error: Unbound module Stream

#=== ERROR while compiling ocamlfind.1.9.2 ====================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.00.0+trunk | https://opam.ocaml.org#53f3d66c
# path                 ~/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/ocamlfind.1.9.2
# command              /usr/bin/make all
# exit-code            2
# env-file             ~/shakti/sandmark/_opam/log/ocamlfind-2576049-45397e.env
# output-file          ~/shakti/sandmark/_opam/log/ocamlfind-2576049-45397e.out
### output ###
# [...]
# ocamlc -I +compiler-libs -opaque    -g -c fl_split.ml
# ocamlc -I +compiler-libs -opaque    -g -c fl_metatoken.ml
# ocamlc -I +compiler-libs -opaque    -g -c fl_meta.ml
# ocamlc -I +compiler-libs -opaque    -c fl_metascanner.mli
# ocamlc -I +compiler-libs -opaque    -g -c fl_metascanner.ml
# File "fl_metascanner.ml", line 41, characters 13-25:
# 41 |           in Stream.lsing (fun _ -> (line, pos, Eof))
#                   ^^^^^^^^^^^^
# Error: Unbound module Stream
# make[1]: *** [Makefile:168: fl_metascanner.cmo] Error 2
# make[1]: Leaving directory '/home/shubham/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/ocamlfind.1.9.2/src/findlib'
# make: *** [Makefile:14: all] Error 2

#=== ERROR while compiling ocamlbuild.0.14.0 ==================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.00.0+trunk | https://opam.ocaml.org#53f3d66c
# path                 ~/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/ocamlbuild.0.14.0
# command              /usr/bin/make check-if-preinstalled all opam-install
# exit-code            2
# env-file             ~/shakti/sandmark/_opam/log/ocamlbuild-2576049-803e1a.env
# output-file          ~/shakti/sandmark/_opam/log/ocamlbuild-2576049-803e1a.out
### output ###
# [...]
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/loc.mli
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/loc.ml
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/discard_printf.mli
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/discard_printf.ml
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/signatures.mli
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/my_std.mli
# ocamlc.opt -w L -w R -w Z -I src -I +unix -safe-string -bin-annot -strict-sequence -c src/my_std.ml
# File "src/my_std.ml", line 127, characters 20-38:
# 127 |       let compare = Pervasives.compare
#                           ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Pervasives
# make: *** [Makefile:422: src/my_std.cmo] Error 2

#=== ERROR while compiling integers.0.5.1 =====================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.00.0+trunk | https://opam.ocaml.org#53f3d66c
# path                 ~/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/integers.0.5.1
# command              ~/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p integers -j 27
# exit-code            1
# env-file             ~/shakti/sandmark/_opam/log/integers-2576049-652035.env
# output-file          ~/shakti/sandmark/_opam/log/integers-2576049-652035.out
### output ###
# Error: The module Pervasives is an alias for module Pervasives, which is missing
# [...]
# (cd _build/default && /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.integers.objs/byte -intf-suffix .ml -no-alias-deps -o src/.integers.objs/byte/unsigned.cmo -c -impl src/unsigned.ml)
# File "src/unsigned.ml", line 104, characters 32-50:
# 104 |   let compare (x : t) (y : t) = Pervasives.compare x y
#                                       ^^^^^^^^^^^^^^^^^^
# Error: The module Pervasives is an alias for module Pervasives, which is missing
#     ocamlopt src/.integers.objs/native/unsigned.{cmx,o} (exit 2)
# (cd _build/default && /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/ocamlopt.opt -w -40 -g -I src/.integers.objs/byte -I src/.integers.objs/native -intf-suffix .ml -no-alias-deps -o src/.integers.objs/native/unsigned.cmx -c -impl src/unsigned.ml)
# File "src/unsigned.ml", line 104, characters 32-50:
# 104 |   let compare (x : t) (y : t) = Pervasives.compare x y
#                                       ^^^^^^^^^^^^^^^^^^
# Error: The module Pervasives is an alias for module Pervasives, which is missing


#=== ERROR while compiling biniou.1.2.1 =======================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.5.00.0+trunk | https://opam.ocaml.org#53f3d66c
# path                 ~/shakti/sandmark/_opam/5.00.0+trunk/.opam-switch/build/biniou.1.2.1
# command              ~/shakti/sandmark/_opam/5.00.0+trunk/bin/dune build -p biniou -j 27
# exit-code            1
# env-file             ~/shakti/sandmark/_opam/log/biniou-2576049-be7d52.env
# output-file          ~/shakti/sandmark/_opam/log/biniou-2576049-be7d52.out
### output ###
#       ocamlc src/.biniou.objs/byte/bi_stream.{cmi,cmti} (exit 2)
# (cd _build/default && /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/bin/ocamlc.opt -safe-string -g -bin-annot -I src/.biniou.objs/byte -I /home/shubham/shakti/sandmark/_opam/5.00.0+trunk/lib/easy-format -no-alias-deps -o src/.biniou.objs/byte/bi_stream.cmi -c -intf src/bi_stream.mli)
# File "src/bi_stream.mli", line 20, characters 59-67:
# 20 | val read_stream : (string -> 'a array) -> in_channel -> 'a Stream.t
#                                                                 ^^^^^^^^
# Error: Unbound module Stream

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build biniou     1.2.1
│ λ build integers   0.5.1
│ λ build ocamlbuild 0.14.0
│ λ build ocamlfind  1.9.2
│ λ build sexplib0   v0.15.0
```

although in the CI these checks seem to be passing without any issues, so there must be some steps I'm leaving out.

for serial runs I'm running the following command
```bash
TAG='"run_in_ci"' make run_config_filtered.json
USE_SYS_DUNE_HACK=1 RUN_CONFIG_JSON=run_config_filtered.json make ocaml-versions/5.00.0+trunk.bench
```
And for parallel runs
```bash
TAG='"run_in_ci"' make multicore_parallel_run_config_filtered.json
TAG='"macro_bench"' make multicore_parallel_run_config_filtered_filtered.json
make multicore_parallel_run_config_filtered_filtered_2domains.json
USE_SYS_DUNE_HACK=1 BUILD_BENCH_TARGET=multibench_parallel RUN_CONFIG_JSON=multicore_parallel_run_config_filtered_filtered_2domains.json make ocaml-versions/5.00.0+trunk.bench
```

I used most of these commands from the `drone.yml` file.
And both the errors were same.

**Comment by kayceesrk** [comment]
https://github.com/ocaml/ocaml/pull/10896 `Pervasives` and `Stream` have been removed.

**Comment by kayceesrk** [comment]
Happy to merge this and continue hacking. Keen to get results sooner rather than later in Sandmark nightly. 

Is there anything pending? @shakthimaan

**Comment by shakthimaan** [comment]
> Is there anything pending?

None AFAIK. Yes, please feel free to merge. Will follow-up with Shubham on the next steps.

**Pull request merged**
