### PR TITLE
Update decompress benchmarks

### PR DESCRIPTION
**Pull request by dinosaure**
A fix about mirage/decompress#86. I added some notes where, about compression, we can take the advantage of multicore - however I let you to see details about that.

### CODE REVIEW

**Comment by shakthimaan** [comment]
I added bigstringaf.0.6.1 as dependency for testing. The test_decompress.exe gets built, but, the following bench run throws an exception:
```
$ cd _build/4.10.0+multicore+caml+state_1/benchmarks/decompress && /home/shakthi/code/sandmark/_opam/4.10.0+multicore+caml+state/bin/orun -o ../../test_decompress.64_524_288.orun.bench -- taskset --cpu-list 5 ./test_decompress.exe 64 524_288Fatal error: exception Invalid_argument("Bigstringaf.blit_to_bytes invalid range: { src_len: 65536, src_off: 65536, dst_len: 4096, dst_off: 0, len: 4096 }")
```
Any suggestions on what are the recommended values?

**Comment by dinosaure** [comment]
Yes, sorry it's about a typo, it should be fixed now.

**Comment by shakthimaan** [comment]
Yes, I am able to build sandmark and run both the serial and parallel benchmarks for Multicore OCaml 4.10.0 with dune.2.5.1. Thanks!

**Comment by anmolsahoo25** [comment]
Needs ```bigstringaf``` in the packages folder.

**Pull request merged**
