### PR TITLE
Issue Solved, Classification of benchmarks.

### PR DESCRIPTION
**Pull request by singhalshubh**
[SEQ] -  Classification of benchmarks
- Updated run_config.json
- Classified into "lt_1s", 1s_10s", "10s_100s",  "gt_100s" as 4 categories.

### CODE REVIEW

**Comment by ctk21** [comment]
This PR is removing the old `tags` and replacing them with just the time attributes.

Given that `tags` is a list of free strings that people can use to filter on, is it possible to add the time attributes but leave the existing `tags`? For example with `cpdf`, I would have expected `tags` to become:
```json
"tags": [
        "macro_bench",
        "run_in_ci",
        "10s_100s"
      ]
```

**Comment by singhalshubh** [comment]
> This PR is removing the old `tags` and replacing them with just the time attributes.
> 
> Given that `tags` is a list of free strings that people can use to filter on, is it possible to add the time attributes but leave the existing `tags`? For example with `cpdf`, I would have expected `tags` to become:
> 
> ```json
> "tags": [
>         "macro_bench",
>         "run_in_ci",
>         "10s_100s"
>       ]
> ```

Hey, I have updated the tags.

**Comment by singhalshubh** [comment]
Updated Multicore too.

**Comment by singhalshubh** [comment]
Micro-Multicore done.

**Pull request merged**
