### PR TITLE
update pausetimes_multicore to fit with the latest Multicore changes

### PR DESCRIPTION
**Pull request by Engil**
This PR aims to address #218 by fixing pausetimes for the 4.12 branches of OCaml.

pausetimes were broken for a while because OCaml changed the way the runtime is instrumented and how we can gather pause metrics from both upstream and Multicore.

The changes boils down to a new format being use (Common Trace Format), as well as a new way to handle how we can ask the runtime to generate such traces in the Multicore variant.

The changes are as follow:
- The 4.12.0 upstream branch:
  - Update the `instrumented` variant of the compiler to `4.12`
  - Have the `pausetime_trunk` script rewritten to pass the right environment variable to start tracing the runtime
  - Use `eventlog-tools` to process the generated trace and generate the expected pausetimes JSON file.

- The 4.12.0 Multicore branch needs:
  - Update the instrumented variant of the compiler to 4.12, and use the `--enable-force-instrumented-runtime` runtime flag to force linking executable against the right runtime when running benchmarks. (see ocaml-multicore/ocaml-multicore#552)
  - Have the `pausetime_multicore` script pass the right environment variables to start tracing the runtime
  - Use `eventlog-tools` to process the generated trace and generated the expected pausetimes JSON file.

A note about eventlog-tools:
Since the runtimes are now using custom formats, we need to use [ocaml-multicore/eventlog-tools](https://github.com/ocaml-multicore/eventlog-tools) to process the traces properly.
This is rather handful because it allows to have processing done in OCaml, and to get a nice speed bump out of it.
This however means two things for this PR:
- We need to add the dependencies to eventlog-tools into the base sandmark dependencies
- eventlog-tools needs to see ocaml-multicore/eventlog-tools#2 merged in order for it to work with this PR. This PR includes handling the correct trace formats for both variants (trunk and multicore), as well as the addition of the pausetimes script.

This PR cannot be merged until the eventlog-tools situation is sorted.
However, in the meantime, I think this PR can be reviewed and improved. (for instance, what should we do about *leftover* code related to older instrumented/eventlog runtime pieces? (like the python scripts?)

### CODE REVIEW

**Comment by shubhamkumar13** [comment]
The following graphs are generated by using the updated pausetimes
- Serial instrumented pausetimes
99_9_percent_latency
99_percent_latency
max_latency
- Parallel instrumented pausetimes
99_percent_latency
max_latency
mean_latency

The snippet in the jupyter notebooks needs a minor update to generate the graphs but it seems to work fine.

**Comment by kayceesrk** [comment]
Looks great!

**Comment by kayceesrk** [comment]
The files `pausetimes/process_eventlog.py` and `pausetimes/process_instrlog.py` are no longer needed IIUC? Can you delete them.

**Comment by Engil** [comment]
I imported a few fixes required that @shubhamkumar13 gave me, as well as the pausetimes files he showed earlier in this PR. (thanks a lot @shubhamkumar13 !)
I also removed the old python script to process eventlogs as suggested by @kayceesrk.

**Comment by shubhamkumar13** [comment]
@Engil This looks good to merge just need to delete the old 4.06.1 instrumented pausetimes .bench files

**Pull request merged**
