### PR TITLE
Port sandmark nightly UI to sandmark notebooks

### PR DESCRIPTION
**Pull request by shubhamkumar13**
This PR upgrades/ports the sandmark notebooks to work with the latest format of files generated by sandmark and also add support for 5.00+stable which currently is supported by sandmark-nightly UI

### CODE REVIEW

**Comment by shakthimaan** [comment]
> support for 5.00+stable

We have now moved to using `5.0.0`. Can you please update the notebooks for the same?

**Comment by shubhamkumar13** [comment]
Rebasing it fixes the `5.0.0` issue, Thanks @shakthimaan for the help!

**Comment by shakthimaan** [comment]
* Can you please update the `README`?
* It will useful to add one more `parallel` benchmark for comparison.
* In `sequential-interactive.ipynb`, the `artifacts_dir` should be `test/artifacts/" for the test samples to work.

**Comment by shubhamkumar13** [comment]
> * Can you please update the `README`?

There is nothing specifically there in notebooks readme or the sandmark readme that needs updating since the version is not specified, if there is something additional to notebooks that needs updating maybe creating a different PR would be the right way to go. Or am I missing something here, let me know :)

**Comment by shakthimaan** [comment]
> nothing specifically there in notebooks readme or the sandmark readme that needs updating since the version is not specified, 

Use newer screenshots and latest version information in the notebooks/README. 
See https://github.com/ocaml-bench/sandmark/tree/main/notebooks

**Comment by shakthimaan** [comment]
LGTM.

**Pull request merged**
