### PR TITLE
Move to latest version of domainslib and saturn

### PR DESCRIPTION
**Pull request by Sudha247**

### CODE REVIEW

**Comment by Sudha247** [comment]
Okay, good news is the CI is happy - I've marked it as ready for review. Question (to @punchagan or @shakthimaan): does the parallel runs include graph500 benchmarks? I saw some failures on it in my local setup with this PR.

**Comment by punchagan** [comment]
> Okay, good news is the CI is happy - I've marked it as ready for review. Question (to @punchagan or @shakthimaan): does the parallel runs include graph500 benchmarks? I saw some failures on it in my local setup with this PR.

Could you share the failures you see? 

From the [latest run](https://github.com/ocaml-bench/sandmark-nightly/commit/06058346167ff890390326ab7746bc99e385ef30) in Navajo, we run `graph500_gen` benchmarks

**Comment by Sudha247** [comment]
The log says

```
$ (cd _build/5.2.0+trunk_1/benchmarks/graph500seq && ./gen.exe -scale 21 -edgefactor 16 edges.data)
> Generating edge list...
[got signal KILL]
$ (cd _build/5.2.0+trunk_1/benchmarks/graph500par && ./gen.exe -scale 21 -edgefactor 16 -ndomains 16 edges.data)
> Generating edge list...
> Generated. Time: 173.464429 s.
```

Maybe the benchmark's just too big for my machine. It might help to do a run on navajo or another larger machine, but otherwise I don't have any other changes to this PR.

**Comment by punchagan** [comment]
> It might help to do a run on navajo or another larger machine

The changes look good to me. I'll do a test run on `navajo` and merge the PR. Thanks for the PR, @Sudha247!

**Pull request merged**
