### PR TITLE
Display raw basline numbers in normalized graphs

### PR DESCRIPTION
**Pull request by shubhamkumar13**
Resolving Issue #176

This change adds raw baseline numbers to the normalized graphs in sequential notebooks

### CODE REVIEW

**Comment by kayceesrk** [comment]
Would it be possible to post a screenshot of how the graph looks now?

**Comment by kayceesrk** [comment]
I took a look at the PR. I have a couple of questions. 

Why do you need the argument "display_name" at all? I see that it is the same everywhere. What purpose does it serve?

image

It appears that we always get the baseline time irrespective of what metric we're interested in (time, major_cycles, minor_cycles, etc). We want the baseline to be the metric that we're plotting. 

image

It would be nice to include a graph title which says what the baseline unit is. Time in seconds, or kilobytes, count, or...

**Comment by shubhamkumar13** [comment]
The idea was to create a different column that contains the display name of the column, `display_name = name + raw_baseline_number`. And pass that column to `catplot` function which displays the labels of the bar graph.
Even now the default parameters to `x_axis_disp` is `name`. Which was the case prior to this PR.
Screenshot from 2020-10-02 16-34-57
The function that generates the plot takes the `x_axis_disp` param. Which may or may not be the name parameter, depends upon what you pass to `x_axis_disp` argument.
Screenshot from 2020-10-02 16-33-21

One thing that was my fault was not realizing that the baseline metrics would be different for different normalized graphs. That would remove `display_name` to be passed to every_function, which looks redundant now.

**Comment by shubhamkumar13** [comment]
I've made changes to reflect the baseline numbers for that metric.
For eg.
I need to pass the metric that I need to display (here gc.top_heap_words)
Screenshot from 2020-10-02 17-23-17
And the baseline numbers in the graph correspond to the same metric
gc_top_heap_words

Similarly, if I were to get a normalized graph for maxrss_kB, it would be something like this.
maxrss_kB

The only change is last argument passed to `add_display_name`, something like this : 
Screenshot from 2020-10-02 17-24-22

**Comment by shubhamkumar13** [comment]
The above code had some redundancy (since `add_display_name` and `normalise` accept same arguments)
I moved them inside `normalise`.

Screenshot from 2020-10-02 18-00-51

This removes the need to explicitly create a new `df` everytime which is implied when we are generating a normalized graph.

**Comment by kayceesrk** [comment]
> The above code had some redundancy (since add_display_name and normalise accept same arguments). I moved them inside normalise.

Shouldn't the 3rd argument to `add_display_name` be `topic`?

**Comment by shubhamkumar13** [comment]
Oh that's bad! that was an overlook on my part.

Not being able to see sane diffs might be a result of this, but I've made the changes, thanks for the help!

So now the top heap words
normalized_gc top_heap_words
and time_secs have their respective baseline
normalization_time_secs

**Comment by kayceesrk** [comment]
Can you post the screenshot for `maxrsskb`? 

I think Shakti wanted the PR to be made against the sequential-interactive notebook. Can we do that in addition to this change @shubhamkumar13?

**Comment by shubhamkumar13** [comment]
This is how the normalized `maxrsskb` graph looks 
max_rss_raw_baseline

**Comment by kayceesrk** [comment]
Thanks!

**Pull request merged**
