### PR TITLE
Mention sudo access for run_all_parallel.sh script

### PR DESCRIPTION
**Pull request by shakthimaan**
$subject

### CODE REVIEW

**Comment by kayceesrk** [comment]
Does run all parallel just needs sudo or sudo with nopasswd? The difference is important since it determines whether the process needs an interactive session. When using without nopasswd, when is the password requested? At the start or after the build phase has completed but before the run phase?

**Comment by shakthimaan** [comment]
Since we want the script to be run non-interactively (such as for nightly builds), we would like the user running the script to have "sudo with nopasswd". With this option the password is not requested at all. Moreover, even for multiple compiler builds, it might be a while before a parallel compiler and its benchmark builds complete, and we do not want to interrupt the script execution and wait for the user to enter the sudo password. The use of sudo is minimized though to only one command in the Makefile when it is required to use chrt.

**Comment by kayceesrk** [comment]
Ok. I think that it would be easier to make sudo access with `nopasswd` a requirement for running parallel benchmarks.

**Comment by kayceesrk** [comment]
Thanks!

**Pull request merged**
