### PR TITLE
Added parallel spectral norm benchmark

### PR DESCRIPTION
**Pull request by kayceesrk**
The speedup is respectable:

```bash
kc@kaveri:~/repos/sandmark$ time ./_build/4.06.1+multicore_1/benchmarks/multicore-numerical/spectralnorm2_multicore.exe 5000 1
1.274224153

real    0m5.123s
user    0m5.117s
sys     0m0.004s
kc@kaveri:~/repos/sandmark$ time ./_build/4.06.1+multicore_1/benchmarks/multicore-numerical/spectralnorm2_multicore.exe 5000 2
1.274224153

real    0m2.704s
user    0m5.260s
sys     0m0.009s
kc@kaveri:~/repos/sandmark$ time ./_build/4.06.1+multicore_1/benchmarks/multicore-numerical/spectralnorm2_multicore.exe 5000 4
1.274224153

real    0m1.552s
user    0m5.722s
sys     0m0.025s
kc@kaveri:~/repos/sandmark$ time ./_build/4.06.1+multicore_1/benchmarks/multicore-numerical/spectralnorm2_multicore.exe 5000 8
1.274224153

real    0m0.921s
user    0m6.566s
sys     0m0.037s
```

The implementation uses bounded channel implementation from the new [domainslib](https://github.com/ocaml-multicore/domainslib). 

Apologies for the noisy PR. I've been ocamlformatting the source code.

### CODE REVIEW

**Comment by ctk21** [comment]
LGTM

Should we add some of the multicore sandmark targets back into `.drone.yml` CI?

**Comment by kayceesrk** [comment]
Good idea. I’ll add them in another PR.

**Comment by kayceesrk** [comment]
@ctk21 Do you want me to do the `.drone.yml` in this PR?

**Comment by ctk21** [comment]
> @ctk21 Do you want me to do the `.drone.yml` in this PR?

No this one is fine, but it's a good idea otherwise the multicore targets could get hit by some other change going forwards.

**Pull request merged**
