### PR TITLE
Add navajo specific parallel config.json file

### PR DESCRIPTION
**Pull request by shubhamkumar13**
This PR adds a custom config.json file which is used by navajo to publish results to [ocaml-bench/sandmark-nightly](https://github.com/ocaml-bench/sandmark-nightly)
(Navajo is a code name for a AMD EPYC 7551 32-Core Processor with 128 cores (2 Numa nodes x 2 sockets x 32 cores). 
Out of the 128 cores only 120 cores are isolated on this machine for benchmarking purpose.)

This PR also renames `multicore_parallel_run_config.json` to `multicore_parallel_iitm_run_config.json` which indicate json file used in nightly benchmarks on the IITM machine.

### CODE REVIEW

**Comment by shakthimaan** [comment]
>  renames multicore_parallel_run_config.json to multicore_parallel_iitm_run_config.json
1. Can we retain the multicore_parallel_run_config file and name as this runs in .drone.yml in a Docker container?
2. Just having a new multicore_parallel_iitm_run_config.json file with the specific machine name will be useful for reference, and if you intend to make any changes in future, we need to disrupt the CI workfowl?

**Comment by shubhamkumar13** [comment]
I agree having a new multicore_parallel_iitm_run_config.json is a better option instead of renaming everything

**Comment by shubhamkumar13** [comment]
Instead of adding a new config file I've added a small note in the readme describing the config files and where there are used.
@shakthimaan let me know your thoughts on this.

**Comment by shakthimaan** [comment]
LGTM.

**Comment by kayceesrk** [comment]
LGTM.

**Pull request merged**
