### PR TITLE
add coq benchmarks which are computationally intensive

### PR DESCRIPTION
**Pull request by shubhamkumar13**
This contains computationally intensive benchmarks present in the frap library.

The running time of the files that are added are mentioned below.(on Turing)

```
CompilerCorrectness - "time_secs":47.790101051330566,"user_time_secs":47.521476,"sys_time_secs":0.268008

TypesAndMutation - "time_secs":106.89803814888,"user_time_secs":106.001234,"sys_time_secs":0.895976

BasicSyntax  - "time_secs":112.15859699249268,"user_time_secs":111.801489,"sys_time_secs":0.355992

DeepAndShallowEmbeddings - "time_secs":30.47971487045288,"user_time_secs":30.219152,"sys_time_secs":0.259992

OperationalSemantics - "time_secs":118.49756097793579,"user_time_secs":118.168615,"sys_time_secs":0.328001

HoareLogic - "time_secs":35.866127014160156,"user_time_secs":35.521523,"sys_time_secs":0.344014

LambdaCalculusAndTypeSoundness - "time_secs":22.50673794746399,"user_time_secs":22.230279,"sys_time_secs":0.275978

SharedMemory - "time_secs":144.47219586372375,"user_time_secs":143.242684,"sys_time_secs":1.227988

AbstractInterpretation - time_secs":320.09168910980225,"user_time_secs":318.381864,"sys_time_secs":1.707988
```

### CODE REVIEW

**Comment by kayceesrk** [comment]
Thanks! Would it also be possible to get the maxrss, number of major and minor collections for these benchmarks?

**Comment by shubhamkumar13** [comment]
@kayceesrk yes I did note them down but since there was nothing interesting about them I thought it was not relevant.
```
CompilerCorrectness - {"allocated_words":9670148124,"minor_words":9665947886,"promoted_words":165505403,"major_words":169705641,"minor_collections":36963,"major_collections":29,"heap_words":37557913,"top_heap_words":40305269,"mean_space_overhead":38.93955}

TypesAndMutation - {"allocated_words":22283729521,"minor_words":22279347144,"promoted_words":398164747,"major_words":402547124,"minor_collections":85099,"major_collections":48,"heap_words":38441441,"top_heap_words":57844341,"mean_space_overhead":39.983265}

BasicSyntax - {"allocated_words":23633155575,"minor_words":23629031066,"promoted_words":328268460,"major_words":332392969,"minor_collections":90241,"major_collections":41,"heap_words":51161111,"top_heap_words":53785205,"mean_space_overhead":37.623428}

OperationalSemantics - {"allocated_words":26558323373,"minor_words":26554182025,"promoted_words":233655022,"major_words":237796370,"minor_collections":101392,"major_collections":35,"heap_words":46439444,"top_heap_words":48194165,"mean_space_overhead":36.010597}

HoareLogic - {"allocated_words":7514713102,"minor_words":7510598347,"promoted_words":86471031,"major_words":90585786,"minor_collections":28729,"major_collections":20,"heap_words":41703221,"top_heap_words":43455093,"mean_space_overhead":17.021636}

LambdaCalculusAndTypeSoundness - {"allocated_words":4443734834,"minor_words":4439676574,"promoted_words":82463893,"major_words":86522153,"minor_collections":17016,"major_collections":20,"heap_words":34243920,"top_heap_words":36778613,"mean_space_overhead":18.134985}

SharedMemory - {"allocated_words":28428060786,"minor_words":28422397783,"promoted_words":421507988,"major_words":427170991,"minor_collections":108529,"major_collections":43,"heap_words":43166239,"top_heap_words":80933493,"mean_space_overhead":29.226501}

AbstractInterpretation - {"allocated_words":71676599939,"minor_words":71672241206,"promoted_words":659874784,"major_words":664233517,"minor_collections":273540,"major_collections":63,"heap_words":49125265,"top_heap_words":90493557,"mean_space_overhead":37.373825}
```

**Comment by kayceesrk** [comment]
`AbstractInterpretation` does an order of magnitude more minor GCs and allocations than some of the benchmarks. Let's keep `BasicSyntax` and `AbstractInterpretation` and remove the rest of the benchmarks.

**Comment by kayceesrk** [comment]
lgtm.

**Pull request merged**
