### PR TITLE
Pin dune and base to work around ocaml trunk changes 

### PR DESCRIPTION
**Pull request by punchagan**
The primary changes in this PR are:

- Pin `base` to workaround Format_doc change (see commit message)
- Pin `dune` to workaround splitting native and bytecode compiler flags (see commit message)

The PR also has other small changes:

- upgrades `dune` to latest version
- Switches OCaml 5.2.0 to 5.2.1
- Fixes broken notebook tests by pinning Python dependencies
- Disable sys dune hack for nightly builds

### CODE REVIEW

**Comment by punchagan** [comment]
CI for OCaml 5.3 is expected to fail due to #471

**Comment by punchagan** [comment]
Pushed a couple of new commits to use a patched version of `dune` to work around the changes in https://github.com/ocaml/ocaml/pull/13201 where the compiler flags for `bytecode` and `native` compilers have been separated out, and name prefixes have been changed to `bytecode_` and `native_` from `ocamlc_` and `ocamlopt_`.

**Comment by punchagan** [comment]
@shakthimaan is my understanding correct that dune would previously not compile against `multicore` branch and `USE_SYS_DUNE_HACK` was required? It seems okay to me to disable this hack and use a patched version of `dune`. Can you please confirm with a review? Thanks!

**Comment by shakthimaan** [comment]
Sure. It will be good to decide on LTS and whether you need to support earlier versions. Otherwise, it is better to upgrade.

**Comment by punchagan** [comment]
Deployed `run_all_custom.sh` script to `navajo`. Remote login to `turing` fails - deployment pending.

**Comment by punchagan** [comment]
[Builds](https://github.com/ocaml-bench/sandmark-nightly/commit/0b597482a68d213688d16c17b0c70156c29c0613) on navajo are running again!

**Pull request merged**
