### PR TITLE
Filter benchmarks based on tag

### PR DESCRIPTION
**Pull request by kayceesrk**
Remove the custom targets `_macro.json` and `_ci.json` and replace that with a generic solution. See #195.

### CODE REVIEW

**Comment by kayceesrk** [comment]
@Sudha247 please see if this is what you were looking for.

**Comment by Sudha247** [comment]
Thanks for this solution @kayceesrk! This is what I was looking for. I have only one suggestion; It might useful to remove `*_filtered.json` during `make clean`. A note on this feature (in the README perhaps) would be helpful, too. :)

**Review by shakthimaan — APPROVED** [review]
LGTM

**Comment by kayceesrk** [comment]
> I have only one suggestion; It might useful to remove *_filtered.json during make clean. A note on this feature (in the README perhaps) would be helpful, too. :)

Done.

**Pull request merged**
