### PR TITLE
adds base

### PR DESCRIPTION
**Pull request by sadiqj**

### CODE REVIEW

**Comment by kayceesrk** [comment]
@sadiqj do we have benchmarks in base library that we can add here.

**Comment by sadiqj** [comment]
> @sadiqj do we have benchmarks in base library that we can add here.

No, we parked this PR because I think we were worried about trunk breaking continuously. It probably wouldn't be hard to port the tests from `stdlib` over.

**Comment by kayceesrk** [comment]
Ok. Better to leave it as it is for now.

**Comment by shakthimaan** [comment]
The following PR https://github.com/ocaml-bench/sandmark/pull/132 updates base to v0.14.0 so that Sandmark can build with dune-2.5.1 and Multicore OCaml 4.10.0, and hence this PR can be closed.

**Pull request closed without merging**
